Fix #1: Completed 7 points
Ajay199903/binary_search_tree pull request #3
Opened 2022-02-08 12:00 UTC by Ajay199903

Add elements into the tree(multiple elements comma separated)
Print the largest element
Print the smallest element
Print Inorder, postorder, level order, and preorder traversal
Search an element
Remove an element
The script should run and serve until quit is not given as input

2022-02-08 16:40 UTC, bv-harsh requested changes

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +class BinarySearchTree
Don't declare two classes in the same file.

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +class Node
We use a tab == 2 spaces.

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +        parent.right_node = Node.new(element)
Two times you have used Node.new, avoid repeatations.

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +    unless node.nil?
Why negating it, when you can directly use ```if node```

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +      unless node.right_node.nil?
Same here

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +    end
why negate, if the same tasks can be achieved directly?

2022-02-08 16:40 UTC, bv-harsh commented on binary_search_tree.rb
> +
Put the classes in two separate files and this main code in a separate file.

2022-02-09 07:06 UTC, Ajay199903 commented on binary_search_tree.rb
> +class BinarySearchTree
Sepearated the classes now

2022-02-09 07:06 UTC, Ajay199903 commented on binary_search_tree.rb
> +class Node
Done

2022-02-09 07:08 UTC, Ajay199903 commented on binary_search_tree.rb
> +        parent.right_node = Node.new(element)
Removed the repeated code

2022-02-09 07:08 UTC, Ajay199903 commented on binary_search_tree.rb
> +    unless node.nil?
Changed it to if statement

2022-02-09 07:09 UTC, Ajay199903 commented on binary_search_tree.rb
> +      unless node.right_node.nil?
Changed to if statement

2022-02-09 07:09 UTC, Ajay199903 commented on binary_search_tree.rb
> +    end
Resolved it with if statement

2022-02-09 07:09 UTC, Ajay199903 commented on binary_search_tree.rb
> +
Done

2022-02-10 05:54 UTC, bv-harsh requested changes
Look for similar issues in the whole code and improve them. Self-review once before giving me back for review

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +      until current.nil?
Isn't ```until current.nil?``` can be written as ```while current```, why use negating, if not required. If negating decreases complexity, then we should use it.

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +    if elements.size
I think this is not required, validated it. Also can elements be nil? If yes this will through error

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +    if node
why if node here?

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +      until queue.empty?
negating required?

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +    end
These are mostly one line if statements, is this not present in coding guidelines:
```
if node
  return search_element(element, node.left_node) if element < node.value
  return search_element(element, node.right_node) if element > node.value
  return true
end

return false

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +        if node.left_node != nil && node.right_node != nil
```node.left_node && node.right_node```

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +  def remove_element(element, node = @root)
Please improve this function, return valid output, like :
Element deleted: element,
Element not found

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +    elsif node.left_node.nil? && node.right_node.nil?
improve

2022-02-10 05:54 UTC, bv-harsh commented on binary_search_tree.rb
> +  def load_bst
I will review this again

2022-02-11 07:07 UTC, merged

2022-02-11 07:34 UTC, Ajay199903 commented
![bst pic 1](https://user-images.githubusercontent.com/53213701/153553039-a67ac869-05a5-4d15-a3d1-538aa311b424.png)
![bst pic 2](https://user-images.githubusercontent.com/53213701/153553048-9f6501c8-a7b6-44a7-ac0f-0d02263c580d.png)
![bst pic 3](https://user-images.githubusercontent.com/53213701/153553060-0ab312ff-bb57-40d1-b620-e6710dce36cf.png)
![bst pic 4](https://user-images.githubusercontent.com/53213701/153553070-f229226f-33ab-47e5-adc2-79c77a9aeb02.png)
![bst pic 5](https://user-images.githubusercontent.com/53213701/153553074-0c63bd3b-39aa-40a1-8f31-bd4b90348233.png)
![bst pic 6](https://user-images.githubusercontent.com/53213701/153553082-58ec3df4-0217-4eff-a608-7d0ad60c8af7.png)